export const PRE_DEFINED_SKILLS: string[] = [
    'Gardening',
    'House Painting',
    'Plumbing',
    'Electrical Work',
    'Babysitting',
    'Tutoring',
    'House Cleaning',
    'Furniture Assembly',
    'Event Staff',
    'Delivery Driver',
    'Pet Sitting',
    'Handyman Services',
    'Basic Carpentry',
    'Graphic Design',
    'Social Media Management',
    'Cooking/Catering',
    'Car Wash/Detailing',
    'Personal Shopping',
    'Elderly Care',
    'Moving Assistance',
];
